services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
      - sakura
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=sakura
      - AI_URL=http://sakura:11434
      - AI_MODEL=qwen3:0.6b
      
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=sakura

  sakura:
    image: appwrite/ollama:0.1.1
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: